server:
  port: 8090
  unsecuredResources: /env,/health,/info,/metrics,/trace,/refresh,/actuator,/prometheus,/services/rest/swagger.json


spring:
  application: tecnicalTest2
  datasource:
    url: jdbc:h2:mem:app;TIME ZONE=UTC
    driverClassName: org.h2.Driver
    username: sa
    password:
  profiles:
    active: capitole-dev
  h2:
    console:
      enabled: true
      path: /console
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath*:mappers/*.xml
logging:
  level:
    com:
      capitole:
        tecnicalTest2: 'DEBUG'
    org.apache.ibatis: 'DEBUG'
flyway:
  enabled: true
  clean-on-validation-error: true